drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

insert into member values (1, 'member1');
insert into member values (2, 'member2');
insert into member values (3, 'member3');
insert into member values (4, 'member4');
insert into member values (5, 'member5');
insert into member values (6, 'member6');