server:
  port: 1234

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    filter: true
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: 0
    docExpansion: none

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com.example.feign.TestFeignClient: DEBUG
