spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://localhost:3307/toy?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: user
  sql:
    init:
      schema-locations: classpath:/schema.sql
---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
