version: "3.9"
services:
  db:
    image: mysql:8.0.29
    container_name: db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "toy"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    volumes:
      - ./mysql:/etc/mysql/conf.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - springboot-mysql-net
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379

networks:
  springboot-mysql-net:
    driver: bridge