version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "toy"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - springboot-mysql-net
  redis:
    image: redis:5.0.6-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379

networks:
  springboot-mysql-net:
    driver: bridge