spring:
  batch:
    initialize-schema: ALWAYS
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MYSQL;
    username: sa
    password:
#    url: jdbc:mysql://localhost:3307/toy
#    username: user
#    password: user
#    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace